### ISSUE TITLE
After Creating a location It tells me Class 'Spatie\OpeningHours\OpeningHours' not found

### ISSUE THREAD

**Issue by artistro08** [OFFLINE-GmbH/oc-opening-hours-plugin#1]
Not sure what this is. here's the stacktrace

```
Symfony\Component\Debug\Exception\FatalThrowableError: Class 'Spatie\OpeningHours\OpeningHours' not found in /home/styleclo/public_html/deviowa/plugins/offline/openinghours/models/Location.php:38
Stack trace:
#0 /home/styleclo/public_html/deviowa/vendor/october/rain/src/Database/Model.php(168): OFFLINE\OpeningHours\Models\Location->afterFetch()
#1 [internal function]: October\Rain\Database\Model->October\Rain\Database\{closure}(Object(OFFLINE\OpeningHours\Models\Location))
#2 /home/styleclo/public_html/deviowa/vendor/october/rain/src/Events/Dispatcher.php(233): call_user_func_array(Object(Closure), Array)
#3 /home/styleclo/public_html/deviowa/vendor/october/rain/src/Events/Dispatcher.php(197): October\Rain\Events\Dispatcher->dispatch('eloquent.fetche...', Array, false)
#4 /home/styleclo/public_html/deviowa/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Concerns/HasEvents.php(148): October\Rain\Events\Dispatcher->fire('eloquent.fetche...', Object(OFFLINE\OpeningHours\Models\Location))
#5 /home/styleclo/public_html/deviowa/vendor/october/rain/src/Database/Model.php(433): Illuminate\Database\Eloquent\Model->fireModelEvent('fetched', false)
#6 /home/styleclo/public_html/deviowa/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(260): October\Rain\Database\Model->newFromBuilder(Object(stdClass))
#7 [internal function]: Illuminate\Database\Eloquent\Builder->Illuminate\Database\Eloquent\{closure}(Object(stdClass))
#8 /home/styleclo/public_html/deviowa/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(261): array_map(Object(Closure), Array)
#9 /home/styleclo/public_html/deviowa/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(1477): Illuminate\Database\Eloquent\Builder->hydrate(Array)
#10 /home/styleclo/public_html/deviowa/vendor/october/rain/src/Extension/ExtendableTrait.php(423): Illuminate\Database\Eloquent\Model->__call('hydrate', Array)
#11 /home/styleclo/public_html/deviowa/vendor/october/rain/src/Database/Model.php(635): October\Rain\Database\Model->extendableCall('hydrate', Array)
#12 /home/styleclo/public_html/deviowa/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(481): October\Rain\Database\Model->__call('hydrate', Array)
#13 /home/styleclo/public_html/deviowa/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(465): Illuminate\Database\Eloquent\Builder->getModels(Array)
#14 /home/styleclo/public_html/deviowa/vendor/october/rain/src/Database/Builder.php(129): Illuminate\Database\Eloquent\Builder->get(Array)
#15 /home/styleclo/public_html/deviowa/modules/backend/widgets/Lists.php(600): October\Rain\Database\Builder->paginate(20, 1)
#16 /home/styleclo/public_html/deviowa/modules/backend/widgets/Lists.php(249): Backend\Widgets\Lists->getRecords()
#17 /home/styleclo/public_html/deviowa/modules/backend/widgets/Lists.php(237): Backend\Widgets\Lists->prepareVars()
#18 /home/styleclo/public_html/deviowa/modules/backend/behaviors/listcontroller/partials/_container.htm(9): Backend\Widgets\Lists->render()
#19 /home/styleclo/public_html/deviowa/modules/system/traits/ViewMaker.php(247): include('/home/styleclo/...')
#20 /home/styleclo/public_html/deviowa/modules/backend/classes/ControllerBehavior.php(153): Backend\Classes\Controller->makeFileContents('/home/styleclo/...', Array)
#21 /home/styleclo/public_html/deviowa/modules/system/traits/ViewMaker.php(97): Backend\Classes\ControllerBehavior->makeFileContents('/home/styleclo/...', Array)
#22 /home/styleclo/public_html/deviowa/modules/backend/behaviors/ListController.php(398): Backend\Classes\ControllerBehavior->makePartial('_container.htm', Array)
#23 /home/styleclo/public_html/deviowa/modules/backend/behaviors/ListController.php(385): Backend\Behaviors\ListController->listMakePartial('container', Array)
#24 [internal function]: Backend\Behaviors\ListController->listRender()
#25 /home/styleclo/public_html/deviowa/vendor/october/rain/src/Extension/ExtendableTrait.php(409): call_user_func_array(Array, Array)
#26 /home/styleclo/public_html/deviowa/modules/backend/classes/Controller.php(192): Backend\Classes\Controller->extendableCall('listRender', Array)
#27 /home/styleclo/public_html/deviowa/plugins/offline/openinghours/controllers/locations/index.htm(1): Backend\Classes\Controller->__call('listRender', Array)
#28 /home/styleclo/public_html/deviowa/modules/system/traits/ViewMaker.php(247): include('/home/styleclo/...')
#29 /home/styleclo/public_html/deviowa/modules/system/traits/ViewMaker.php(109): Backend\Classes\Controller->makeFileContents('/home/styleclo/...')
#30 /home/styleclo/public_html/deviowa/modules/backend/classes/Controller.php(412): Backend\Classes\Controller->makeView('index')
#31 /home/styleclo/public_html/deviowa/modules/backend/classes/Controller.php(286): Backend\Classes\Controller->execPageAction('index', Array)
#32 /home/styleclo/public_html/deviowa/modules/backend/classes/BackendController.php(161): Backend\Classes\Controller->run('index', Array)
#33 [internal function]: Backend\Classes\BackendController->run('offline/opening...')
#34 /home/styleclo/public_html/deviowa/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): call_user_func_array(Array, Array)
#35 /home/styleclo/public_html/deviowa/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(45): Illuminate\Routing\Controller->callAction('run', Array)
#36 /home/styleclo/public_html/deviowa/vendor/laravel/framework/src/Illuminate/Routing/Route.php(212): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(Backend\Classes\BackendController), 'run')
#37 /home/styleclo/public_html/deviowa/vendor/laravel/framework/src/Illuminate/Routing/Route.php(169): Illuminate\Routing\Route->runController()
#38 /home/styleclo/public_html/deviowa/vendor/laravel/framework/src/Illuminate/Routing/Router.php(658): Illuminate\Routing\Route->run()
#39 /home/styleclo/public_html/deviowa/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(30): Illuminate\Routing\Router->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#40 /home/styleclo/public_html/deviowa/modules/backend/classes/BackendController.php(68): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#41 /home/styleclo/public_html/deviowa/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(131): Backend\Classes\BackendController->Backend\Classes\{closure}(Object(Illuminate\Http\Request), Object(Closure))
#42 /home/styleclo/public_html/deviowa/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#43 /home/styleclo/public_html/deviowa/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(41): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#44 /home/styleclo/public_html/deviowa/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\Routing\Middleware\SubstituteBindings->handle(Object(Illuminate\Http\Request), Object(Closure))
#45 /home/styleclo/public_html/deviowa/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#46 /home/styleclo/public_html/deviowa/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#47 /home/styleclo/public_html/deviowa/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\View\Middleware\ShareErrorsFromSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#48 /home/styleclo/public_html/deviowa/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#49 /home/styleclo/public_html/deviowa/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(63): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#50 /home/styleclo/public_html/deviowa/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\Session\Middleware\StartSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#51 /home/styleclo/public_html/deviowa/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#52 /home/styleclo/public_html/deviowa/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#53 /home/styleclo/public_html/deviowa/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle(Object(Illuminate\Http\Request), Object(Closure))
#54 /home/styleclo/public_html/deviowa/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#55 /home/styleclo/public_html/deviowa/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(66): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#56 /home/styleclo/public_html/deviowa/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\Cookie\Middleware\EncryptCookies->handle(Object(Illuminate\Http\Request), Object(Closure))
#57 /home/styleclo/public_html/deviowa/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#58 /home/styleclo/public_html/deviowa/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#59 /home/styleclo/public_html/deviowa/vendor/laravel/framework/src/Illuminate/Routing/Router.php(660): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#60 /home/styleclo/public_html/deviowa/vendor/laravel/framework/src/Illuminate/Routing/Router.php(635): Illuminate\Routing\Router->runRouteWithinStack(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request))
#61 /home/styleclo/public_html/deviowa/vendor/laravel/framework/src/Illuminate/Routing/Router.php(601): Illuminate\Routing\Router->runRoute(Object(Illuminate\Http\Request), Object(Illuminate\Routing\Route))
#62 /home/styleclo/public_html/deviowa/vendor/october/rain/src/Router/CoreRouter.php(20): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#63 /home/styleclo/public_html/deviowa/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(176): October\Rain\Router\CoreRouter->dispatch(Object(Illuminate\Http\Request))
#64 /home/styleclo/public_html/deviowa/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(30): Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}(Object(Illuminate\Http\Request))
#65 /home/styleclo/public_html/deviowa/plugins/offline/responsiveimages/classes/ResponsiveImagesMiddleware.php(30): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#66 /home/styleclo/public_html/deviowa/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): OFFLINE\ResponsiveImages\Classes\ResponsiveImagesMiddleware->handle(Object(Illuminate\Http\Request), Object(Closure))
#67 /home/styleclo/public_html/deviowa/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#68 /home/styleclo/public_html/deviowa/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(46): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#69 /home/styleclo/public_html/deviowa/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure))
#70 /home/styleclo/public_html/deviowa/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#71 /home/styleclo/public_html/deviowa/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#72 /home/styleclo/public_html/deviowa/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(151): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#73 /home/styleclo/public_html/deviowa/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(116): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#74 /home/styleclo/public_html/deviowa/index.php(43): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#75 {main}
```

**Comment by tobias-kuendig** [comment]
How did you install the plugin?

**Comment by artistro08** [comment]
From the market

**Comment by tobias-kuendig** [comment]
This looks like a problem with the build process:
https://github.com/octobercms/october/issues/4043#issuecomment-515454729

For the time being you can run `composer require spatie/opening-hours` to fix the issue manually.

Thank you for the report!

**Comment by artistro08** [comment]
Thank you. That fixes it. You think it would be a good idea if you updated
the documentation in the plug-in temporarily?
